### ISSUE TITLE
Crash in confocal while changing color bar

### ISSUE THREAD

**Issue by drogenlied** [drogenlied/qudi#69]
**Reported by drogenlied on 3 Nov 2015 14:56 UTC**
This is a new one

Fatal Python error: Segmentation fault

Thread 0x000292fc (most recent call first):
  File "C:\Anaconda3\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 24 in mafunction
  File "<string>", line 2 in function
  File "C:\software\QuDi\hardware\ni_card.py", line 1008 in _write_scanner_ao
  File "C:\software\QuDi\hardware\ni_card.py", line 1197 in scan_line
  File "C:\software\QuDi\logic\confocal_logic.py", line 479 in _scan_line

Thread 0x0002928c (most recent call first):
  File "C:\Anaconda3\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 24 in mafunction
  File "<string>", line 2 in function
  File "C:\software\QuDi\hardware\ni_card.py", line 607 in get_counter
  File "C:\software\QuDi\logic\counter_logic.py", line 363 in countLoopBody_continuous

Thread 0x00029244 (most recent call first):
  File "C:\Anaconda3\lib\site-packages\zmq\utils\garbage.py", line 47 in run
  File "C:\Anaconda3\lib\threading.py", line 920 in _bootstrap_inner
  File "C:\Anaconda3\lib\threading.py", line 888 in _bootstrap

Thread 0x00029224 (most recent call first):
  File "C:\Anaconda3\lib\threading.py", line 290 in wait
  File "C:\Anaconda3\lib\threading.py", line 553 in wait
  File "C:\Anaconda3\lib\site-packages\IPython\core\history.py", line 791 in run
  File "C:\Anaconda3\lib\site-packages\IPython\core\history.py", line 68 in needs_sqlite
  File "<string>", line 2 in run
  File "C:\Anaconda3\lib\threading.py", line 920 in _bootstrap_inner
  File "C:\Anaconda3\lib\threading.py", line 888 in _bootstrap

Thread 0x00029204 (most recent call first):
  File "C:\Anaconda3\lib\socket.py", line 187 in accept
  File "C:\Anaconda3\lib\site-packages\rpyc\utils\server.py", line 128 in accept
  File "C:\Anaconda3\lib\site-packages\rpyc\utils\server.py", line 241 in start
  File "C:\software\QuDi\core\remote.py", line 168 in run

Current thread 0x000291fc (most recent call first):
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 692 in get_xy_cb_range
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1418 in refresh_xy_image
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1360 in update_xy_cb_range
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1343 in shortcut_to_xy_cb_centiles
  File "C:\software\QuDi\core\__main__.py", line 198 in <module>
  File "C:\Anaconda3\lib\runpy.py", line 85 in _run_code
  File "C:\Anaconda3\lib\runpy.py", line 170 in _run_module_as_main

**Comment by drogenlied** [comment]
**Comment by latchr on 4 Nov 2015 09:54 UTC**
I was able to reproduce this once on my laptop running dummy hardware.  I got very similar output as shown below.  I have tried numerous times to reproduce this, but have not been able to even when I adjust the colorbar scale at high frequency.

---------------------------------------------

Fatal Python error: Segmentation fault

Thread 0x00007f7dd5be9700 (most recent call first):
  File "/home/lachlan/physics/code/qudi/logic/fit_logic.py", line 103 in twoD_gaussian_function
  File "/home/lachlan/physics/code/qudi/hardware/confocal_scanner_interface_dummy.py", line 313 in scan_line
  File "/home/lachlan/physics/code/qudi/logic/confocal_logic.py", line 479 in _scan_line

Thread 0x00007f7df2c46700 (most recent call first):
  File "/usr/lib64/python3.4/site-packages/zmq/utils/garbage.py", line 45 in run
  File "/usr/lib64/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib64/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f7df3e4c700 (most recent call first):
  File "/usr/lib64/python3.4/threading.py", line 290 in wait
  File "/usr/lib64/python3.4/threading.py", line 553 in wait
  File "/usr/lib64/python3.4/site-packages/IPython/core/history.py", line 791 in run
  File "/usr/lib64/python3.4/site-packages/IPython/core/history.py", line 68 in needs_sqlite
  File "<string>", line 2 in run
  File "/usr/lib64/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib64/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f7e01ee2700 (most recent call first):
  File "/usr/lib64/python3.4/socket.py", line 187 in accept
  File "/usr/lib64/python3.4/site-packages/rpyc/utils/server.py", line 128 in accept
  File "/usr/lib64/python3.4/site-packages/rpyc/utils/server.py", line 241 in start
  File "/home/lachlan/physics/code/qudi/core/remote.py", line 168 in run

Current thread 0x00007f7e172dc700 (most recent call first):
  File "/home/lachlan/physics/code/qudi/gui/confocal/confocalgui.py", line 692 in get_xy_cb_range
  File "/home/lachlan/physics/code/qudi/gui/confocal/confocalgui.py", line 744 in refresh_xy_colorbar
  File "/home/lachlan/physics/code/qudi/gui/confocal/confocalgui.py", line 1422 in refresh_xy_image
  File "/home/lachlan/physics/code/qudi/gui/confocal/confocalgui.py", line 1360 in update_xy_cb_range
  File "/home/lachlan/physics/code/qudi/gui/confocal/confocalgui.py", line 1343 in shortcut_to_xy_cb_centiles
  File "/home/lachlan/physics/code/qudi/core/__main__.py", line 198 in <module>
  File "/usr/lib64/python3.4/runpy.py", line 85 in _run_code
  File "/usr/lib64/python3.4/runpy.py", line 170 in _run_module_as_main
Unexpected return value -11. Exiting.
Traceback (most recent call last):
  File "./start.py", line 40, in <module>
    sys.exit(retval)
SystemExit: -11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./start.py", line 45, in <module>
    process.kill()
  File "/usr/lib64/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib64/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [3](Errno) No such process

**Comment by drogenlied** [comment]
**Comment by a-stark on 11 Mar 2016 23:35 UTC**
Hi guys, 
in my opinion, the error messages are not telling really what has happened and which causes the Segmentation Fault. I would say that their crash is just the result of something, which happens before (which is not caught by the Traceback).
I can reproduce the error 'relatively reliable' by pressing the confocal to scan and changing with the mouse wheel at first the upper centiles and directly afterwards moving with the mouse wheel the lower centiles back and forth. 
Moreover, I do not think that we would be able to trace that error back to its origin, I believe that is a very tricky bug either in in Qt or even in the c-code of the python interpreter. I would guess it has to do with the dereferencing of a value passed by a signal of Qt. 
But you can obviously see the problem here: The burst of signals resulting from changing the spinbox will eventually change the colorbar itself and the picture, which have cross dependencies during the signal sent process. So my suggestion is actually quite simple: Use a SignalProxy to reduce the burst of emitted signals during the scan (I have added the file QuDi-dev\Playground\proxy-for-signals.py some time ago exactly for that purpose). I believe that would solve the problem. I.e. deconnect the change of the spinbox upon start of the scan and connect  before scan actually starts the value change via the SignalProxy to reduce the signals (you will actually not feel the difference if signals are reduced to max every 50ms or higher). If the scan stops or is finished, deconnect the Proxy and connect the normal changed method.
Or make it simple and connect the proxy the whole time with the value changed signal. 

;)

If you have time to do it you are free to go, I would only have time for that after the pulsed environment works properly.

**Comment by drogenlied** [comment]
**Comment by drogenlied on 17 Mar 2016 13:12 UTC**
Up to date backtrace:

Fatal Python error: Segmentation fault

Thread 0x000016c4 (most recent call first):
  File "C:\Anaconda3\envs\qudi\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 25 in mafunction
  File "<string>", line 2 in function
  File "C:\software\QuDi\hardware\ni_card.py", line 1160 in _write_scanner_ao
  File "C:\software\QuDi\hardware\ni_card.py", line 1345 in scan_line
  File "C:\software\QuDi\logic\confocal_logic.py", line 664 in _scan_line

Thread 0x00001c14 (most recent call first):
  File "C:\software\QuDi\core\parentpoller.py", line 105 in run
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 920 in _bootstrap_inner
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 888 in _bootstrap

Thread 0x000014b0 (most recent call first):
  File "C:\Anaconda3\envs\qudi\lib\site-packages\zmq\utils\garbage.py", line 47 in run
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 920 in _bootstrap_inner
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 888 in _bootstrap

Thread 0x00001ddc (most recent call first):
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 290 in wait
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 553 in wait
  File "C:\Anaconda3\envs\qudi\lib\site-packages\IPython\core\history.py", line 798 in run
  File "C:\Anaconda3\envs\qudi\lib\site-packages\IPython\core\history.py", line 68 in needs_sqlite
  File "<decorator-gen-23>", line 2 in run
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 920 in _bootstrap_inner
  File "C:\Anaconda3\envs\qudi\lib\threading.py", line 888 in _bootstrap

Thread 0x00001bd0 (most recent call first):
  File "C:\Anaconda3\envs\qudi\lib\socket.py", line 187 in accept
  File "C:\Anaconda3\envs\qudi\lib\site-packages\rpyc\utils\server.py", line 128 in accept
  File "C:\Anaconda3\envs\qudi\lib\site-packages\rpyc\utils\server.py", line 241 in start
  File "C:\software\QuDi\core\remote.py", line 184 in run

Current thread 0x00000d78 (most recent call first):
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 735 in get_xy_cb_range
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 778 in refresh_xy_colorbar
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1472 in refresh_xy_image
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1410 in update_xy_cb_range
  File "C:\software\QuDi\gui\confocal\confocalgui.py", line 1393 in shortcut_to_xy_cb_centiles
  File "C:\software\QuDi\core\__main__.py", line 233 in <module>
  File "C:\Anaconda3\envs\qudi\lib\runpy.py", line 85 in _run_code
  File "C:\Anaconda3\envs\qudi\lib\runpy.py", line 170 in _run_module_as_main


The offending line is:

            # Exclude any zeros (which are typically due to unfinished scan)
            xy_image_nonzero = self.xy_image.image[ np.nonzero(self.xy_image.image) ]
